#! /usr/bin/env python
#
# Support module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Feb 24, 2018 06:27:58 PM


import sys
import gui

top = None


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def Feed():
    print('ClientGUI_support.Feed')
    sys.stdout.flush()

def on1L():
    print('ClientGUI_support.on1L')
    sys.stdout.flush()

def on1R():
    print('ClientGUI_support.on1R')
    sys.stdout.flush()

def on2L():
    print('ClientGUI_support.on2L')
    sys.stdout.flush()

def on2R():
    print('ClientGUI_support.on2R')
    sys.stdout.flush()

def onExit():
    print('ClientGUI_support.onExit')
    sys.stdout.flush()
    sys.exit(1)

def onRunTraining():
    print('ClientGUI_support.onRunTraining')
    sys.stdout.flush()

def onSendtest():
    print('ClientGUI_support.onSendtest')
    sys.stdout.flush()

def onStatClear():
    global top, w
    print('ClientGUI_support.onStatClear')
    sys.stdout.flush()
    #top.txtStatLog.delete('0', END)

def onStatRun():
    print('ClientGUI_support.onStatRun')
    sys.stdout.flush()


def init(topw, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = topw
    root = topw

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


#if __name__ == '__main__':
root = Tk()
app = gui.GUIClass(root, )
#top = Main.Fish_traning_GUI_Client(root)
top.fillValue()
top.txtStatLog.insert('0.0', 'TETET')
init(root, top)


root.wm_attributes("-topmost", 1)
root.focus_force()
root.mainloop()


