#! /usr/bin/env python
#
# Support module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Feb 24, 2018 06:27:58 PM
#    Apr 23, 2018 08:54:50 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def set_Tk_var():
    global FeedVar
    FeedVar = StringVar()

def onLogClear():
    print('ClientGUI_support.onLogClear')
    sys.stdout.flush()


def Feed():
    print('ClientGUI_support.Feed')
    sys.stdout.flush()

def on1L():
    print('ClientGUI_support.on1L')
    sys.stdout.flush()

def on1R():
    print('ClientGUI_support.on1R')
    sys.stdout.flush()

def on2L():
    print('ClientGUI_support.on2L')
    sys.stdout.flush()

def on2R():
    print('ClientGUI_support.on2R')
    sys.stdout.flush()

def onExit():
    global exit_var
    print('ClientGUI_support.onExit')
    sys.stdout.flush()

    exit_var = True
    sys.exit(1)

def onRunTraining():
    print('ClientGUI_support.onRunTraining')
    sys.stdout.flush()

def onStopTraining(top):
    global stop_traning
    sys.stdout.flush()
    stop_traning=True
    #app.txtMainLog.insert(END, 'Stopped!')
    top.print_and_update_main_log("test")
    #print_and_update_main_log

def onSendtest():
    print('ClientGUI_support.onSendtest')
    sys.stdout.flush()

def onStatClear():
    print('ClientGUI_support.onStatClear')
    sys.stdout.flush()

def onStatRun():
    print('ClientGUI_support.onStatRun')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ClientGUI
    ClientGUI.vp_start_gui()





